# Generated by Django 6.0.5 on 2026-05-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
